"""empty message

Revision ID: 7d006bd1591d
Revises: 23ca2865ae62
Create Date: 2024-04-07 21:46:12.947424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d006bd1591d'
down_revision = '23ca2865ae62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_index('ix_favorite_movie_title')
        batch_op.drop_index('ix_favorite_movie_id')
        batch_op.create_index(batch_op.f('ix_favorite_movie_id'), ['movie_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_movie_id'))
        batch_op.create_index('ix_favorite_movie_id', ['movie_id'], unique=1)
        batch_op.create_index('ix_favorite_movie_title', ['movie_title'], unique=False)

    # ### end Alembic commands ###
